### ISSUE TITLE
[機能リクエスト]クリップボードからの画像添付

### ISSUE THREAD

**Issue by bee7813993** [nkte8/skyshare#1]
よくスクリーンショットをSNSに画像として添付することが多いので、画像をクリップボードからのペーストで添付できると助かります。

**Comment by nkte8** [comment]
@bee7813993 さん、機能リクエストありがとうございます！こちらのIssueは Issue formの整備により移行させていただきました! 
状況の確認を行いたい場合は、#2 へ Subscribeしていただければ幸いです。

上記対応により、本Issueはクローズさせていただきます。
