### ISSUE TITLE
[Bug Report]: Blueskyでリンクカードが適切に追加できない （フォークで仮修正済み）

### ISSUE THREAD

**Issue by ZEKE320** [nkte8/skyshare#11]
### What's the matter?

URLを含むポストを作成した際に、Bluesky側でリンクカードとして登録できていません。
ログを見る限り、URLが同一オリジンポリシーに引っかかりエラーとなっているようです。

![スクリーンショット 2024-02-21 182834](https://github.com/nkte8/skyshare/assets/46393375/b9f85fae-e798-46e6-b4cf-672708ad9e08)
![スクリーンショット 2024-02-21 183104](https://github.com/nkte8/skyshare/assets/46393375/be3b112f-d760-48cd-975f-abb15bfb0874)

### When/How the issue was occured?

- 環境
  - Skyshare v1.1.8
- 手順
  - 任意のURLをポストに含め、"Post"を押下する

### What environmet you using to cause issue?

- OS
  - Windows 11 Home (23H2)
- ブラウザ
  - Google Chrome, version: 121.0.6167.185
  - Microsoft Edge, version: 121.0.2277.128

### Can you occur issue again?

任意のURLをポストに含めた状態で、"Post"を押して投稿する

### Other infomation pls.

ドラフトPRを追加しました → https://github.com/nkte8/skyshare/pull/12

**Comment by nkte8** [comment]
@ZEKE320 バグ報告＆ドラフトPRの発行ありがとうございます！
#5 で同じ問題に遭遇していました。確認しますね。

**Comment by nkte8** [comment]
# 状況報告

報告遅れて申し訳ありません。

頂いたPRを参考にコードを改善しました。 5d0e750672635a2b74849915d273180dfb4db881
しかし、無料提供範囲におけるCloudflare Worker上での`fetch`処理の実行は10msecでおさまっていないらしく、処理中のデータがレスポンスとして返されてしまうことを確認しました。

こちらは`fetch`に10msec以上かかっていることを示すCloud flare PagesのWorker(preview)のfunctionsメトリクス、稼働時間の情報(実行日時間にフィルタリングしてます)
![IMG_0101](https://github.com/nkte8/skyshare/assets/91360587/03f2e43f-a251-4eec-a23c-2526b0bc4c80)

# 今後の対処について

現在firebaseへの関数の移動を実施中です。

ただし、この関数自体が汎用的であり悪用の可能性があると考えています。
OAuthといった仕組みにより関数を守る部分も開発する必要があると思っており、これについても併せてどのようにするか等を検討中です。

一旦は認証を追加する前段階まで進んだ時点で、 @ZEKE320 氏にコードレビューをお願いしようと考えています。

**Comment by ZEKE320** [comment]
確認しました！
共有ありがとうございます

**Comment by nkte8** [comment]
# 状況の更新
先のコメント https://github.com/nkte8/skyshare/issues/11#issuecomment-1963248918 ですが、誤りがありました。

> 無料提供範囲におけるCloudflare Worker上でのfetch処理の実行は10msecでおさまっていないらしく、処理中のデータがレスポンスとして返されてしまうことを確認しました。

こちら状況把握が誤っていました。Astroの`hybrid`モードについては、SSRモードでの動作を明示しないと、**APIRouteについても正しく動作しない様子でした。**
この情報は[ドキュメント上](https://docs.astro.build/ja/guides/endpoints/#サーバーエンドポイントapiルーティング)では以下のように表現されていました。
> ノート
これらの例を試す前に、必ず[SSRを有効](https://docs.astro.build/ja/guides/server-side-rendering/)にしてください。

こちら明示的にSSRであることを宣言するフラグを追加したところ、Cloudflare上でも正しくAPIが動作することを確認できました。
このため、firebaseへの関数移管は不要となり、当初のコミット通りAstroAPIルーティングの機能を使うことができました。

PRを発行しました！確認お願いします。

**Comment by nkte8** [comment]
v1.3.0にて対処完了
