### ISSUE TITLE
[Feature Request]: ストレージの変更

### ISSUE THREAD

**Issue by nkte8** [nkte8/skyshare#12]
### Request Details

今後の運用を考えた際、Firebase StorageよりCloudflare R2を採用した方が良いため、これを置き換える。

### Feature Scope

other, write next (その他。次のフォームに記載する)

### Feature Add infomation

今後の運用のための変更

**Comment by nekono-dev** [comment]
https://whtwnd.com/nekono.dev/entries/test
whtwnd.com はbluesky PDS上にmarkdownを保存・管理が可能なAppView
この実装と同様に、画像データやページデータをPDSへ保管できないか？

**Comment by nekono-dev** [comment]
本Issueはbluesky PDSを利用する形として別途のIssueとして再定義する。
