### ISSUE TITLE
[Feature Request]: @atproto/common-web の採用

### ISSUE THREAD

**Issue by nkte8** [nkte8/skyshare#15]
### Request Details

ATProtoのlexiconを追い続けてコードを改修するのが辛い。また、プラットフォームとしてユーザを抱えており、できる限り安定させたい。
そのため、どこかのタイミングでAT Protoの技術共有としての開発を終了し、純粋なアプリケーションの開発パターンとしての展開に切り替えたい。

@atproto/common-webはWebアプリケーション上でAT Protocolを動かすことを目的とした公式産のnpmライブラリであり、導入を検討したい。

なお本作業が終了する際は、ATProtoの技術共有としての面はタグ打ちを行い、Zennへの記事の改訂をもって完了としたい。

### Feature Scope

other, write next (その他。次のフォームに記載する)

### Feature Add infomation

開発効率の向上・改善

**Comment by nekono-dev** [comment]
そもそもcommon-webにagentが含まれていない、採用ライブラリを再検討としクローズ
