### ISSUE TITLE
[Improve code]: OGP取得方法の改善

### ISSUE THREAD

**Issue by nkte8** [nkte8/skyshare#28]
### Where and how it seems bad?

現在、OGPの画像取得は `getOgpMeta.ts`にてfetchを用いて実行しており、HTMLの解析処理は正規表現にて実施している。
```ts
        const htmlBlob: Blob = await fetch(url
        ).then((res) => res.blob()).catch((res: Error) => {
            let e: Error = new Error(res.message)
            e.name = res.name
            throw e
        })
        const encoding: string = await findEncoding(htmlBlob)
        const html: string = unescapeHtml(
            await decodeAsText(htmlBlob, encoding)
        )
        const meta: ogpMetaData = extractHead(html);
        const response = new Response(
            JSON.stringify(meta),
            {
                status: 200,
                headers: headers
            })
        return response
```

### What it shoud become?

Cloudflareが提供している HTMLRewriter と呼ばれるParserを使うことで、この部分が改善できるのではないか。
参考: 
- https://zenn.dev/uyas/articles/0b7dcbb46d8031
- https://blog.cloudflare.com/ja-jp/html-rewriter-beta-ja-jp

**Comment by nekono-dev** [comment]
こちらのIssueの優先度を下げます。
- Cloudflareを使い続けたいが、Cloudflare独自の仕様のあるプロダクトを使うのはリスキーである
- むしろ現在実施している正規表現での検索をより抽象化し、ブラウザネイティブなHTMLParserを自作してしまったほうがわかりやすく、将来的である

**Comment by nekono-dev** [comment]
すでにParserに置き換えられた #43 クローズ
