### ISSUE TITLE
[Feature Request]: クリップボードからの画像添付

### ISSUE THREAD

**Issue by nkte8** [nkte8/skyshare#3]
### Request Details

よくスクリーンショットをSNSに画像として添付することが多いので、画像をクリップボードからのペーストで添付できると助かります。

### Feature Scope

Usability increase, user satisfication (ユーザビリティ向上させ、利用者を満足させる)

**Comment by nekono-dev** [comment]
以下は以前ZEKE氏に相談した内容の転記です
----

@ZEKE320 遅くなりましたが確認しました！対応ありがとうございます🙇
2点機能の面での相談があります。
1. MacOSだと以下のような感じで文字列が含まれてしまうみたいです。お手元でこの辺って確認できそうでしょうか。
<img width="675" alt="スクリーンショット 2024-03-12 19 19 55" src="https://github.com/nkte8/skyshare/assets/91360587/e9f9d3c5-f022-4c61-a0d8-c3f0f198b3df">

2.  #2 の要件を見る感じなんとなくですが、画像ファイルのコピー&ペーストではなく、画像データ（例えばPrintScreenにて得た画像情報）のコピーペーストに対応してほしいように見えています（もちろん両方あるに越したことはないのですが）これって対応できそうでしょうか。

**Comment by nekono-dev** [comment]
v1.3.5 で対応
