### ISSUE TITLE
[Bug Report]: InstagramのOGPが表示されない

### ISSUE THREAD

**Issue by nkte8** [nkte8/skyshare#30]
### What's the matter?

InstagramからOGPを取得できず、リンクカードが正しく挿入されない。

### When/How the issue was occured?

Instagramのリンクを添付したポストを実施しようとすると、OGP画像が取得できない

### What environmet you using to cause issue?

環境依存なし

### Can you occur issue again?

1. 投稿フォームを開く
2. Instagramのリンクを添付する
3. 送信を行う

**Comment by nekono-dev** [comment]
リンクカードの手動取得対応に伴い、外部URLの対応非対応が容易に確認できるようになった。
上記課題の根本解決は難しいが、一旦投稿が想定通りにならないことによる不満はなくなるのではないだろうか、という部分で整理している

**Comment by nekono-dev** [comment]
一旦は対応を行わない整理としてクローズ（状況代わり次第再オープン）
