### ISSUE TITLE
[Feature Request]: リッチテキストの投稿サポート

### ISSUE THREAD

**Issue by atNllA** [nkte8/skyshare#9]
### Request Details

blueskyでは投稿にリッチテキストを用いて装飾やリンクを添付することができる。ATプロト(blueskyプラットフォーム寄りではあるが)習熟兼ねて実装したい。

### Feature Scope

Better for Bluesky user, more wonderful (Blueskyユーザに対して、より魅力的にする), Awesome idea, increase Developer motivation (素晴らしいアイデアで、開発者を躍起にさせる)

**Comment by nkte8** [comment]
そもそもまだリッチテキストでできることはリンクの添付程度（facetの機能）だけであるため、命題自体が不適切です。クローズします。
